<script src="public/vendor/global/global.min.js" type="text/javascript"></script>
<script src="public/vendor/bootstrap-select/dist/js/bootstrap-select.min.js" type="text/javascript"></script>
<script src="public/vendor/chart.js/Chart.bundle.min.js" type="text/javascript"></script>
<script src="public/vendor/owl-carousel/owl.carousel.js" type="text/javascript"></script>
<script src="public/vendor/apexchart/apexchart.js" type="text/javascript"></script>
<script src="public/js/dashboard/dashboard-1.js" type="text/javascript"></script>
<script src="public/vendor/toastr/js/toastr.min.js" type="text/javascript"></script>
<script src="public/js/plugins-init/toastr-init.js" type="text/javascript"></script>
<script src="public/vendor/datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="public/js/plugins-init/datatables.init.js" type="text/javascript"></script>
<script src="public/js/custom.min.js" type="text/javascript"></script>
<script src="public/js/deznav-init.js" type="text/javascript"></script>